@startuml
'https://plantuml.com/class-diagram

abstract class Bird {
   String name
   String color
   abstract speak()
   fly()
 }

class Pigeon {
    eatPizza()
    sleep()
}


Bird <|-- Pigeon

abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml