@startuml
'https://plantuml.com/class-diagram

interface Dance{
    spin()
    doTheCaterpillar()
    jump()
}

abstract class Bird implements Dance {
   String name
   String color
   abstract speak()
   fly()
 }

class Pigeon {
    speak()
    eatPizza()
    sleep()
}

class Parrot{
speak()
}

Bird <|-- Pigeon
Bird <|-- Parrot

abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml